from knackpy.exceptions import ValidationError



class Record:
    def __init__(self, id_key="id", data=None):
        